[theme]
primaryColor="#7c3aed"              # Ritual-leaning purple
backgroundColor="#0f172a"           # Deep navy
secondaryBackgroundColor="#111827"  # Dark panel
textColor="#e5e7eb"                 # Soft white
font="sans serif"
